mysql:
  host: "localhost"
  port: 3306
  database: "factory_db"
  user: ""
  password: ""

excel:
  path: ""
  sheet_name: "Equipos"

datamart:
  host: "localhost"
  port: 5432
  database: "datamart_practica_diusframi"
  user: ""
  password: ""

etl:
  start_date: "2025-01-01"
  batch_days: 7
  festivity_country: "ES"
  festivity_region: "AN"