mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  database: ${MYSQL_DATABASENAME}
  user: ${MYSQL_USERNAME}
  password: ${MYSQL_USERPASSWORD}

excel:
  path: ${EXCEL_PATH}
  sheet_name: ${EXCEL_SHEET_NAME}

datamart:
  host: ${DM_HOST}
  port: ${DM_PORT}
  database: ${DM_DBNAME}
  user: ${DM_USER}
  password: ${DM_PASSWORD}

etl:
  start_date: "2025-01-01"
  batch_days: 7
  festivity_country: "ES"
  festivity_region: "AN"